New SDF project
Checking a new SDF project for the instacart use case in DBT that was checked into the rep. I am only checking in one of the ETL stages i.e. stg_orders, because I ran into some SDF bugs when I did SDF describe. Specifically, I am seeing:

error: Unsupported argument types. Can not evaluate Float64 * Interval(MonthDayNano)
error: No DML statement found in multi-statement query